(() => {
  'use strict';
  const tg = window.Telegram?.WebApp;
  const tenant = document.body.dataset.tenant;
  const initData = tg?.initData || '';
  const previewMode = location.protocol === 'file:' || ['localhost', '127.0.0.1'].includes(location.hostname);
  let currentStatus = 'all';
  let candidatePage = 0;
  let candidateQuery = '';
  let searchTimer;
  let modalResolve;
  const statusNames = {pending:'Yangi',saved:'Keyin ko‘rish',accepted:'Suhbatga',declined:'Rad etilgan',rejected_hard_filter:'Filtrdan o‘tmadi',rejected_irrelevant:'Mos kelmadi',rejected_ai_generated:'Shubhali',hired:'Ishga olindi',not_hired:'Ishga olinmadi',no_show:'Suhbatga kelmadi'};
  const esc = value => String(value ?? '').replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const fmt = n => new Intl.NumberFormat('uz-UZ').format(n);
  const initials = name => String(name || '?').split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase();
  const previewData = {
    dashboard: {company:'Apus Group',stats:{pending:8,accepted:14,total:67},active_vacancies:3,recent:[
      {id:1,full_name:'Ali Otajonov',vacancy_title:'Sotuv menejeri',status:'pending',score:82},
      {id:2,full_name:'Dilnoza Karimova',vacancy_title:'SMM mutaxassisi',status:'pending',score:76},
      {id:3,full_name:'Javohir Akramov',vacancy_title:'Sotuv menejeri',status:'saved',score:64}],
      billing:{plan:'BUSINESS',applications_used:67,applications_limit:100}},
    candidates:{items:[
      {id:1,full_name:'Ali Otajonov',vacancy_title:'Sotuv menejeri',phone_number:'+998 90 123 45 67',status:'pending',score:82},
      {id:2,full_name:'Dilnoza Karimova',vacancy_title:'SMM mutaxassisi',phone_number:'+998 93 777 21 10',status:'pending',score:76},
      {id:3,full_name:'Javohir Akramov',vacancy_title:'Sotuv menejeri',phone_number:'+998 95 555 10 20',status:'saved',score:64},
      {id:4,full_name:'Madina Ergasheva',vacancy_title:'Buxgalter',phone_number:'+998 99 111 32 10',status:'accepted',score:88}]},
    vacancies:{items:[{key:'sales',title:'Sotuv menejeri',active:true,total:38,pending:5,questions:10},{key:'smm',title:'SMM mutaxassisi',active:true,total:19,pending:2,questions:8},{key:'accountant',title:'Buxgalter',active:true,total:10,pending:1,questions:9}]},
    interviews:{total:4,scheduled:[
      {id:4,full_name:'Madina Ergasheva',vacancy_title:'Buxgalter',selected_slot:'2026-09-02 10:30',score:88},
      {id:5,full_name:'Sardor Mamatqulov',vacancy_title:'Sotuv menejeri',selected_slot:'2026-09-03 15:00',score:80}],
      awaiting_slot:[{id:6,full_name:'Nodira Aliyeva',vacancy_title:'SMM mutaxassisi',score:78},{id:7,full_name:'Akmal Yusupov',vacancy_title:'Sotuv menejeri',score:74}],
      slots:[{id:1,label:'2-sentabr, 10:30',capacity:2,booked:1},{id:2,label:'3-sentabr, 15:00',capacity:3,booked:1}],
      settings:{location_text:'Toshkent shahri, Chilonzor tumani',interviewer_name:'Aziz Rahimov',interviewer_phone:'+998 90 123 45 67',notes:'Belgilangan vaqtdan 10 daqiqa oldin keling.'}},
    billing:{current:{code:'business',name:'BUSINESS',expires_at:'2026-09-30T00:00:00'},plans:[{code:'start',name:'START',price:299000,applications:50,vacancies:1},{code:'growth',name:'GROWTH',price:599000,applications:200,vacancies:3},{code:'business',name:'BUSINESS',price:1190000,applications:600,vacancies:10}]}
  };
  const previewDashboard = () => {const items=previewData.candidates.items;const pending=8+(items.filter(c=>c.status==='pending').length-2);const accepted=14+(items.filter(c=>c.status==='accepted').length-1);return {...previewData.dashboard,stats:{pending,accepted,total:67},active_vacancies:previewData.vacancies.items.filter(v=>v.active).length,recent:[...items].sort((a,b)=>b.id-a.id).slice(0,3)};};
  const previewInterviews = () => {const scheduled=[...previewData.interviews.scheduled];const awaiting=[...previewData.interviews.awaiting_slot];for(const c of previewData.candidates.items.filter(c=>c.status==='accepted')){if(!scheduled.some(x=>x.id===c.id)&&!awaiting.some(x=>x.id===c.id))awaiting.unshift({...c});}return {scheduled,awaiting_slot:awaiting,total:scheduled.length+awaiting.length,slots:previewData.interviews.slots,settings:previewData.interviews.settings};};
  const previewCandidate = id => {const all=[...previewData.candidates.items,...previewData.interviews.scheduled,...previewData.interviews.awaiting_slot];const c=all.find(item=>item.id===Number(id))||previewData.candidates.items[0];return {...c,phone_number:c.phone_number||'+998 90 123 45 67',answers:{experience:'Shu yo‘nalishda 1,5 yil amaliy tajribam bor.',tools:'CRM va kundalik hisobot tizimlari bilan ishlaganman.',achievement:'Bir oyda rejaning 118 foizini bajarganman.',plan:'Birinchi haftada vazifalarni o‘rganib, aniq ish rejasini tuzaman.'},ai_scores:{achievement:{score:88,izoh:'Natija aniq raqam bilan tasdiqlangan.'},plan:{score:79,izoh:'Reja tushunarli, o‘lchovlarini kuchaytirish mumkin.'}}};};
  const api = async (path, options={}) => {
    if(previewMode){
      await new Promise(resolve=>setTimeout(resolve,120));
      if(path==='/dashboard') return previewDashboard();
      const decisionMatch=path.match(/^\/candidates\/(\d+)\/decision$/);if(decisionMatch&&options.method==='POST'){const c=previewData.candidates.items.find(item=>item.id===Number(decisionMatch[1]));if(!c)throw new Error('Nomzod topilmadi.');const action=JSON.parse(options.body||'{}').action;c.status={accept:'accepted',save:'saved',reject:'declined'}[action]||c.status;return {ok:true,status:c.status};}
      const detailMatch=path.match(/^\/candidates\/(\d+)$/);if(detailMatch)return previewCandidate(detailMatch[1]);
      if(path.startsWith('/candidates')){const params=new URLSearchParams(path.split('?')[1]||'');const q=(params.get('q')||'').toLowerCase();const status=params.get('status');const items=previewData.candidates.items.filter(c=>(!status||status==='all'||c.status===status)&&(!q||`${c.full_name} ${c.phone_number} ${c.vacancy_title}`.toLowerCase().includes(q)));return {items,total:items.length,page:Number(params.get('page')||0)};}
      const vacancyMatch=path.match(/^\/vacancies\/([^/]+)\/toggle$/);if(vacancyMatch&&options.method==='POST'){const vacancy=previewData.vacancies.items.find(v=>v.key===decodeURIComponent(vacancyMatch[1]));if(!vacancy)throw new Error('Vakansiya topilmadi.');vacancy.active=!vacancy.active;return {ok:true,active:vacancy.active};}
      const outcomeMatch=path.match(/^\/candidates\/(\d+)\/outcome$/);if(outcomeMatch&&options.method==='POST'){const c=previewData.candidates.items.find(item=>item.id===Number(outcomeMatch[1]));if(!c)throw new Error('Nomzod topilmadi.');c.status=JSON.parse(options.body||'{}').outcome;return {ok:true,status:c.status};}
      if(path==='/vacancies'&&options.method==='POST'){const body=JSON.parse(options.body||'{}');const key=body.title.toLowerCase().replace(/[^a-z0-9]+/g,'_');previewData.vacancies.items.unshift({key,title:body.title,active:true,total:0,pending:0,questions:body.questions.length,reject_message:body.reject_message,resume_required:body.resume_required,question_items:body.questions.map((text,index)=>({key:`q${index+1}`,text}))});return {ok:true,key};}
      const vacancyEditMatch=path.match(/^\/vacancies\/([^/]+)$/);if(vacancyEditMatch){const vacancy=previewData.vacancies.items.find(v=>v.key===decodeURIComponent(vacancyEditMatch[1]));if(!vacancy)throw new Error('Vakansiya topilmadi.');if(options.method==='PUT'){const body=JSON.parse(options.body||'{}');Object.assign(vacancy,{title:body.title,questions:body.questions.length,reject_message:body.reject_message,resume_required:body.resume_required,question_items:body.questions.map((text,index)=>({key:`q${index+1}`,text}))});return {ok:true,key:vacancy.key};}return {...vacancy,questions:vacancy.question_items||Array.from({length:vacancy.questions},(_,i)=>({key:`q${i+1}`,text:`${i+1}-saralash savoli`})),reject_message:vacancy.reject_message||'Arizangiz uchun rahmat. Hozircha keyingi bosqichga o‘tmadingiz.',resume_required:Boolean(vacancy.resume_required)};}
      if(path.startsWith('/vacancies')) return previewData.vacancies;
      if(path==='/interviews/slots'&&options.method==='POST'){const body=JSON.parse(options.body||'{}');const slot={id:Date.now(),label:body.label,capacity:Number(body.capacity)||1,booked:0};previewData.interviews.slots.push(slot);return {ok:true,slot};}
      const deleteSlotMatch=path.match(/^\/interviews\/slots\/(\d+)$/);if(deleteSlotMatch&&options.method==='DELETE'){previewData.interviews.slots=previewData.interviews.slots.filter(s=>s.id!==Number(deleteSlotMatch[1]));return {ok:true};}
      if(path==='/interviews/settings'&&options.method==='POST'){previewData.interviews.settings={...JSON.parse(options.body||'{}')};return {ok:true,settings:previewData.interviews.settings};}
      if(/^\/interviews\/\d+\/remind$/.test(path)&&options.method==='POST')return {ok:true};
      if(path==='/interviews') return previewInterviews();
      if(path==='/billing') return previewData.billing;
      return {ok:true};
    }
    const response = await fetch(`/api/miniapp/${tenant}${path}`, {...options, headers:{'Content-Type':'application/json','X-Telegram-Init-Data':initData,...options.headers}});
    if (!response.ok) throw new Error((await response.text()) || 'Server xatosi');
    return response.json();
  };
  function toast(message){const el=document.querySelector('#toast');el.textContent=message;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2200);}
  function closeModal(result=false){const modal=document.querySelector('#action-modal');modal.hidden=true;modal.className='modal';if(modalResolve){modalResolve(result);modalResolve=null;}}
  function ask({title,text,confirm='Tasdiqlash',icon='?',type='',single=false}){const modal=document.querySelector('#action-modal');modal.className=`modal ${type} ${single?'single':''}`.trim();document.querySelector('#modal-title').textContent=title;document.querySelector('#modal-text').textContent=text;document.querySelector('#modal-icon').textContent=icon;document.querySelector('#modal-confirm').textContent=confirm;modal.hidden=false;return new Promise(resolve=>{modalResolve=resolve;});}
  function scoreClass(score){return score >= 75 ? '' : score >= 55 ? 'mid' : 'low';}
  function candidateRow(c){return `<button class="candidate" data-candidate="${c.id}"><span class="avatar">${esc(initials(c.full_name))}</span><span class="candidate-body"><h3>${esc(c.full_name)}</h3><p>${esc(c.vacancy_title)}</p><span class="status ${esc(c.status)}">${esc(statusNames[c.status]||c.status)}</span></span><span class="score ${scoreClass(c.score)}">${c.score == null?'—':esc(c.score)}</span></button>`;}
  function show(name){document.querySelectorAll('.view').forEach(x=>x.classList.toggle('active',x.id===name));const navName=name==='interview-settings'?'interviews':name;document.querySelectorAll('.bottom-nav button').forEach(x=>x.classList.toggle('active',x.dataset.go===navName));document.querySelector('.bottom-nav').hidden=name==='detail'||name==='error-view';window.scrollTo(0,0);if(name==='dashboard')loadDashboard();if(name==='candidates'){candidatePage=0;loadCandidates();}if(name==='interviews')loadInterviews();if(name==='interview-settings')loadInterviewSettings();if(name==='vacancies')loadVacancies();if(name==='billing')loadBilling();}
  async function loadDashboard(){try{const d=await api('/dashboard');document.querySelector('#company').textContent=d.company;document.querySelector('#hero-vacancies').textContent=`${d.active_vacancies} faol vakansiya`;document.querySelector('#hero-interviews').textContent=`${d.stats.accepted} ta suhbat`;document.querySelector('#m-pending').textContent=d.stats.pending;document.querySelector('#m-accepted').textContent=d.stats.accepted;document.querySelector('#m-vacancies').textContent=d.active_vacancies;document.querySelector('#m-total').textContent=d.stats.total;const urgent=document.querySelector('#urgent');urgent.hidden=!d.stats.pending;document.querySelector('#urgent-count').textContent=`${d.stats.pending} ta yangi nomzod`;document.querySelector('#recent-list').innerHTML=d.recent.length?d.recent.map(candidateRow).join(''):'<div class="empty">Hozircha ariza yo‘q.</div>';document.querySelector('#plan-name').textContent=d.billing.plan;const limit=d.billing.applications_limit??'∞';document.querySelector('#plan-usage').textContent=`${d.billing.applications_used} / ${limit} ariza ishlatildi`;const percent=Number.isFinite(Number(limit))?Math.min(100,Math.round((d.billing.applications_used/Number(limit))*100)):0;document.querySelector('.plan-progress span').style.width=`${percent}%`;}catch(e){fail(e);}}
  async function loadCandidates({append=false}={}){const list=document.querySelector('#candidate-list');const more=document.querySelector('#load-more');if(!append)list.innerHTML='<div class="empty">Yuklanmoqda…</div>';more.hidden=true;try{const params=new URLSearchParams({status:currentStatus,page:String(candidatePage)});if(candidateQuery)params.set('q',candidateQuery);const d=await api(`/candidates?${params}`);const rows=d.items.map(candidateRow).join('');if(append)list.insertAdjacentHTML('beforeend',rows);else list.innerHTML=rows||'<div class="empty">Mos nomzod topilmadi.</div>';more.hidden=(candidatePage+1)*20>=d.total||!d.items.length;}catch(e){fail(e);}}
  function interviewCard(c,waiting=false){if(waiting)return `<article class="waiting-card"><span class="avatar">${esc(initials(c.full_name))}</span><button class="interview-person" data-candidate="${c.id}"><span class="interview-body"><h3>${esc(c.full_name)}</h3><p>${esc(c.vacancy_title)}</p></span></button><button class="remind-btn" data-remind="${c.id}">Eslatish</button></article>`;const raw=String(c.selected_slot||'');const match=raw.match(/(\d{4})-(\d{2})-(\d{2})[ T](\d{2}:\d{2})/);const months=['Yan','Fev','Mar','Apr','May','Iyun','Iyul','Avg','Sen','Okt','Noy','Dek'];const day=match?match[3]:'—';const month=match?months[Number(match[2])-1]:'';const time=match?match[4]:raw;return `<button class="interview-card" data-candidate="${c.id}"><span class="interview-date"><b>${esc(day)}</b><small>${esc(month)}</small></span><span class="interview-body"><h3>${esc(c.full_name)}</h3><p>${esc(c.vacancy_title)}</p><div class="interview-time">${esc(time)}</div></span><span class="score ${scoreClass(c.score)}">${c.score==null?'—':esc(c.score)}</span></button>`;}
  async function loadInterviews(){const scheduled=document.querySelector('#scheduled-list');const awaiting=document.querySelector('#awaiting-list');scheduled.innerHTML=awaiting.innerHTML='<div class="empty">Yuklanmoqda…</div>';try{const d=await api('/interviews');document.querySelector('#i-total').textContent=d.total;document.querySelector('#i-scheduled').textContent=d.scheduled.length;document.querySelector('#i-waiting').textContent=d.awaiting_slot.length;scheduled.innerHTML=d.scheduled.length?d.scheduled.map(c=>interviewCard(c)).join(''):'<div class="empty">Rejalashtirilgan suhbat yo‘q.</div>';awaiting.innerHTML=d.awaiting_slot.length?d.awaiting_slot.map(c=>interviewCard(c,true)).join(''):'<div class="empty">Vaqt tanlashni kutayotgan nomzod yo‘q.</div>';}catch(e){fail(e);}}
  function renderSlots(slots){const list=document.querySelector('#slot-list');list.innerHTML=slots.length?slots.map(slot=>{const percent=Math.min(100,Math.round((slot.booked/slot.capacity)*100));return `<div class="slot-item"><div><b>${esc(slot.label)}</b><small>${slot.booked} / ${slot.capacity} joy band</small></div><span class="slot-usage"><span style="width:${percent}%"></span></span><button data-delete-slot="${slot.id}" data-slot-label="${esc(slot.label)}" aria-label="Vaqtni o‘chirish">×</button></div>`;}).join(''):'<div class="slot-empty">Hozircha suhbat vaqti qo‘shilmagan.</div>';}
  async function loadInterviewSettings(){try{const d=await api('/interviews');renderSlots(d.slots||[]);const s=d.settings||{};document.querySelector('#setting-location').value=s.location_text||'';document.querySelector('#setting-name').value=s.interviewer_name||'';document.querySelector('#setting-phone').value=s.interviewer_phone||'';document.querySelector('#setting-notes').value=s.notes||'';}catch(e){fail(e);}}
  async function addSlot(event){event.preventDefault();const label=document.querySelector('#slot-label').value.trim();const capacity=Number(document.querySelector('#slot-capacity').value);if(!label)return;try{await api('/interviews/slots',{method:'POST',body:JSON.stringify({label,capacity})});event.target.reset();document.querySelector('#slot-capacity').value='1';toast('Suhbat vaqti qo‘shildi');loadInterviewSettings();}catch(e){toast(e.message);}}
  async function saveInterviewSettings(event){event.preventDefault();const body={location_text:document.querySelector('#setting-location').value.trim(),interviewer_name:document.querySelector('#setting-name').value.trim(),interviewer_phone:document.querySelector('#setting-phone').value.trim(),notes:document.querySelector('#setting-notes').value.trim()};try{await api('/interviews/settings',{method:'POST',body:JSON.stringify(body)});tg?.HapticFeedback?.notificationOccurred('success');toast('Suhbat sozlamalari saqlandi');show('interviews');}catch(e){toast(e.message);}}
  async function deleteSlot(button){if(!await ask({title:'Suhbat vaqtini o‘chirish',text:`${button.dataset.slotLabel} ro‘yxatdan olib tashlanadi.`,confirm:'O‘chirish',icon:'!',type:'danger'}))return;try{await api(`/interviews/slots/${button.dataset.deleteSlot}`,{method:'DELETE'});toast('Suhbat vaqti o‘chirildi');loadInterviewSettings();}catch(e){toast(e.message);}}
  async function remindCandidate(id){if(!await ask({title:'Vaqt tanlashni eslatish',text:'Nomzodga bo‘sh suhbat vaqtlarini tanlash uchun qayta xabar yuboriladi.',confirm:'Eslatma yuborish',icon:'↗'}))return;try{await api(`/interviews/${id}/remind`,{method:'POST',body:'{}'});tg?.HapticFeedback?.notificationOccurred('success');toast('Eslatma yuborildi');}catch(e){toast(e.message);}}
  async function loadVacancies(){const list=document.querySelector('#vacancy-list');list.innerHTML='<div class="empty">Yuklanmoqda…</div>';try{const d=await api('/vacancies');list.innerHTML=d.items.length?d.items.map(v=>`<article class="vacancy"><div class="vacancy-head"><div><h3>${esc(v.title)}</h3><p>${v.active?'Nomzodlar uchun ochiq':'Yopilgan'}</p></div><button class="toggle ${v.active?'on':''}" data-toggle-vacancy="${esc(v.key)}" aria-label="Holatni o‘zgartirish"></button></div><div class="vacancy-meta"><span>${v.total} ariza</span><span>${v.pending} yangi</span><span>${v.questions} savol</span></div><div class="vacancy-actions"><button data-edit-vacancy="${esc(v.key)}">Tahrirlash</button><button data-export-vacancy="${esc(v.key)}" data-title="${esc(v.title)}">Excel eksport</button></div></article>`).join(''):'<div class="empty">Hozircha vakansiya yo‘q. “Yangi” tugmasi orqali yarating.</div>';}catch(e){fail(e);}}
  function resetVacancyForm(){document.querySelector('#vacancy-form').reset();document.querySelector('#vacancy-key').value='';document.querySelector('#vacancy-editor-title').textContent='Yangi vakansiya';document.querySelector('#vacancy-reject').value='Arizangiz uchun rahmat. Hozircha keyingi bosqichga o‘tmadingiz. Sizga muvaffaqiyat tilaymiz!';show('vacancy-editor');}
  async function editVacancy(key){try{const v=await api(`/vacancies/${encodeURIComponent(key)}`);document.querySelector('#vacancy-key').value=v.key;document.querySelector('#vacancy-editor-title').textContent='Vakansiyani tahrirlash';document.querySelector('#vacancy-title').value=v.title;document.querySelector('#vacancy-questions').value=(v.questions||[]).map(q=>q.text).join('\n');document.querySelector('#vacancy-reject').value=v.reject_message;document.querySelector('#vacancy-resume').checked=Boolean(v.resume_required);show('vacancy-editor');}catch(e){toast(e.message);}}
  async function saveVacancy(event){event.preventDefault();const key=document.querySelector('#vacancy-key').value;const questions=document.querySelector('#vacancy-questions').value.split('\n').map(x=>x.trim()).filter(Boolean);if(questions.length<3||questions.length>20){toast('3 tadan 20 tagacha savol kiriting');return;}const body={title:document.querySelector('#vacancy-title').value.trim(),questions,reject_message:document.querySelector('#vacancy-reject').value.trim(),resume_required:document.querySelector('#vacancy-resume').checked};try{await api(key?`/vacancies/${encodeURIComponent(key)}`:'/vacancies',{method:key?'PUT':'POST',body:JSON.stringify(body)});tg?.HapticFeedback?.notificationOccurred('success');toast(key?'Vakansiya yangilandi':'Vakansiya yaratildi');show('vacancies');}catch(e){toast(e.message);}}
  async function exportVacancy(key,title){if(previewMode){toast('Demo rejimida Excel eksport tayyor');return;}try{const response=await fetch(`/api/miniapp/${tenant}/vacancies/${encodeURIComponent(key)}/export`,{headers:{'X-Telegram-Init-Data':initData}});if(!response.ok)throw new Error((await response.text())||'Eksport xatosi');const blob=await response.blob();const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download=`${title||'nomzodlar'}.xlsx`;document.body.appendChild(link);link.click();link.remove();URL.revokeObjectURL(url);toast('Excel fayl tayyor');}catch(e){toast(e.message);}}
  async function loadBilling(){try{const d=await api('/billing');document.querySelector('#current-plan').innerHTML=`<small>JORIY TARIF</small><h2>${esc(d.current.name)}</h2><p>${d.current.expires_at?'Amal qiladi: '+esc(d.current.expires_at.slice(0,10)):'Sinov rejimi'}</p>`;document.querySelector('#plans').innerHTML=d.plans.map(p=>`<article class="price-card ${p.code==='growth'?'popular':''}">${p.code==='growth'?'<span class="popular-tag">OMMABOP</span>':''}<div class="price-head"><div><h3>${esc(p.name)}</h3><p>${p.applications} ariza · ${p.vacancies} vakansiya</p></div></div><div class="price">${fmt(p.price)} so‘m</div><button data-open-bot data-plan="${esc(p.name)}" data-price="${p.price}">${p.code===d.current.code?'Tarifni yangilash':'Tarifni tanlash'}</button></article>`).join('');}catch(e){fail(e);}}
  async function openCandidate(id){try{const returnView=document.querySelector('.view.active')?.id==='interviews'?'interviews':'candidates';const back=document.querySelector('#detail-back');back.dataset.go=returnView;back.textContent=returnView==='interviews'?'← Suhbatlar':'← Nomzodlar';const c=await api(`/candidates/${id}`);const questionNames={experience:'Tajribangiz haqida ayting',tools:'Qaysi ish vositalarini bilasiz?',crm:'Qaysi CRM tizimlarida ishlagansiz?',achievement:'Eng yaxshi natijangiz qanday?',plan:'Ishni nimadan boshlaysiz?'};const answers=Object.entries(c.answers||{}).map(([key,value])=>{const ai=c.ai_scores?.[key];return `<div class="answer"><b>${esc(questionNames[key]||'SAVOLGA JAVOB')}</b><p>${esc(value)}</p>${ai?.izoh?`<div class="ai-note">${esc(ai.izoh)}${ai.score!=null?` · ${esc(ai.score)}/100`:''}</div>`:''}</div>`}).join('');const actions=['pending','saved'].includes(c.status)?`<div class="decision-actions"><button data-decision="accept" data-id="${c.id}">Suhbatga chaqirish</button><button class="save" data-decision="save" data-id="${c.id}">Keyin ko‘rish</button><button class="reject" data-decision="reject" data-id="${c.id}">Rad etish</button></div>`:c.status==='accepted'?`<div class="outcome-actions"><button class="hired" data-outcome="hired" data-id="${c.id}">✓ Ishga olindi</button><button class="no-show" data-outcome="no_show" data-id="${c.id}">Suhbatga kelmadi</button><button class="not-hired" data-outcome="not_hired" data-id="${c.id}">Ishga olinmadi</button></div>`:'';document.querySelector('#candidate-detail').innerHTML=`<article class="detail-card"><span class="status ${esc(c.status)}">${esc(statusNames[c.status]||c.status)}</span><h1>${esc(c.full_name)}</h1><div class="detail-meta">${esc(c.vacancy_title)} · ${esc(c.phone_number||'Raqam yo‘q')}</div><div class="detail-score"><span>AI moslik bahosi</span><strong>${c.score==null?'—':esc(c.score)+'/100'}</strong></div>${answers||'<div class="empty">Javoblar topilmadi.</div>'}${actions}</article>`;show('detail');}catch(e){toast(e.message);}}
  async function decide(id,action){const config={accept:{title:'Suhbatga chaqirish',text:'Nomzodga mavjud suhbat vaqtlarini tanlash uchun xabar yuboriladi.',confirm:'Chaqirish',icon:'✓',type:'success'},save:{title:'Keyin ko‘rish',text:'Nomzod saqlanadi va “Keyin” filtrida qoladi.',confirm:'Saqlash',icon:'↗'},reject:{title:'Nomzodni rad etish',text:'Nomzodga rad javobi yuboriladi. Bu qarorni tekshirib tasdiqlang.',confirm:'Rad etish',icon:'!',type:'danger'}};if(!await ask(config[action]))return;try{const result=await api(`/candidates/${id}/decision`,{method:'POST',body:JSON.stringify({action})});tg?.HapticFeedback?.notificationOccurred('success');toast(result.warning||'Qaror saqlandi');show(action==='accept'?'interviews':'candidates');}catch(e){toast(e.message);}}
  async function setOutcome(id,outcome){const names={hired:'Ishga olindi',not_hired:'Ishga olinmadi',no_show:'Suhbatga kelmadi'};if(!await ask({title:names[outcome],text:'Bu natija yollash statistikasiga saqlanadi.',confirm:'Natijani saqlash',icon:outcome==='hired'?'✓':'!',type:outcome==='hired'?'success':'danger'}))return;try{await api(`/candidates/${id}/outcome`,{method:'POST',body:JSON.stringify({outcome})});tg?.HapticFeedback?.notificationOccurred('success');toast('Yakuniy natija saqlandi');show('interviews');}catch(e){toast(e.message);}}
  async function toggleVacancy(key){try{const result=await api(`/vacancies/${encodeURIComponent(key)}/toggle`,{method:'POST',body:'{}'});tg?.HapticFeedback?.impactOccurred('light');toast(result.active?'Vakansiya ochildi':'Vakansiya yopildi');loadVacancies();}catch(e){toast(e.message);}}
  async function choosePlan(button){const plan=button.dataset.plan;const price=fmt(Number(button.dataset.price));const approved=await ask({title:`${plan} tarifi`,text:`${price} so‘m. To‘lov va tarifni faollashtirish admin botda davom etadi.`,confirm:'Botda davom etish',icon:'₸'});if(!approved)return;if(tg?.close)tg.close();else toast('Demo rejimida botga qaytish o‘chirilgan.');}
  function fail(error){document.querySelector('#error-message').textContent=error.message||'Mini Appni admin bot ichidan qayta oching.';show('error-view');}
  document.addEventListener('click',e=>{if(e.target.closest('[data-modal-close]')){closeModal(false);return;}if(e.target.closest('#modal-confirm')){closeModal(true);return;}const go=e.target.closest('[data-go]');if(go)show(go.dataset.go);const candidate=e.target.closest('[data-candidate]');if(candidate)openCandidate(candidate.dataset.candidate);const filter=e.target.closest('[data-status]');if(filter){currentStatus=filter.dataset.status;candidatePage=0;document.querySelectorAll('[data-status]').forEach(x=>x.classList.toggle('active',x===filter));loadCandidates();}const decision=e.target.closest('[data-decision]');if(decision)decide(decision.dataset.id,decision.dataset.decision);const outcome=e.target.closest('[data-outcome]');if(outcome)setOutcome(outcome.dataset.id,outcome.dataset.outcome);const toggle=e.target.closest('[data-toggle-vacancy]');if(toggle)toggleVacancy(toggle.dataset.toggleVacancy);const edit=e.target.closest('[data-edit-vacancy]');if(edit)editVacancy(edit.dataset.editVacancy);const exportButton=e.target.closest('[data-export-vacancy]');if(exportButton)exportVacancy(exportButton.dataset.exportVacancy,exportButton.dataset.title);const deleteButton=e.target.closest('[data-delete-slot]');if(deleteButton)deleteSlot(deleteButton);const remind=e.target.closest('[data-remind]');if(remind)remindCandidate(remind.dataset.remind);const plan=e.target.closest('[data-open-bot]');if(plan)choosePlan(plan);});
  document.addEventListener('keydown',e=>{const action=e.target.closest?.('.metric-action');if(action&&(e.key==='Enter'||e.key===' ')){e.preventDefault();show(action.dataset.go);}});
  const searchInput=document.querySelector('#candidate-search');
  searchInput.addEventListener('input',()=>{candidateQuery=searchInput.value.trim();searchInput.closest('.search-box').classList.toggle('has-value',Boolean(candidateQuery));clearTimeout(searchTimer);searchTimer=setTimeout(()=>{candidatePage=0;loadCandidates();},280);});
  document.querySelector('#clear-search').addEventListener('click',()=>{searchInput.value='';candidateQuery='';searchInput.closest('.search-box').classList.remove('has-value');candidatePage=0;loadCandidates();searchInput.focus();});
  document.querySelector('#load-more').addEventListener('click',()=>{candidatePage+=1;loadCandidates({append:true});});
  document.querySelector('#slot-form').addEventListener('submit',addSlot);
  document.querySelector('#interview-settings-form').addEventListener('submit',saveInterviewSettings);
  document.querySelector('#vacancy-form').addEventListener('submit',saveVacancy);
  document.querySelector('#new-vacancy').addEventListener('click',resetVacancyForm);
  document.querySelector('#refresh').addEventListener('click',()=>show(document.querySelector('.view.active')?.id||'dashboard'));
  document.querySelector('#retry').addEventListener('click',()=>show('dashboard'));
  document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!document.querySelector('#action-modal').hidden)closeModal(false);});
  tg?.ready();tg?.expand();tg?.setHeaderColor?.('#ffffff');tg?.setBackgroundColor?.('#f5f7fb');
  if(!initData&&!previewMode){fail(new Error('Mini Appni kompaniyangizning Admin botidagi “Boshqaruv paneli” tugmasidan oching.'));}else{loadDashboard();}
})();
