(() => {
  'use strict';
  const tg = window.Telegram?.WebApp;
  const tenant = document.body.dataset.tenant;
  const initData = tg?.initData || '';
  let currentStatus = 'all';
  const statusNames = {pending:'Yangi',saved:'Keyin ko‘rish',accepted:'Suhbatga',declined:'Rad etilgan',rejected_hard_filter:'Filtrdan o‘tmadi',rejected_irrelevant:'Mos kelmadi',rejected_ai_generated:'Shubhali'};
  const esc = value => String(value ?? '').replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const fmt = n => new Intl.NumberFormat('uz-UZ').format(n);
  const initials = name => String(name || '?').split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase();
  const api = async (path, options={}) => {
    const response = await fetch(`/api/miniapp/${tenant}${path}`, {...options, headers:{'Content-Type':'application/json','X-Telegram-Init-Data':initData,...options.headers}});
    if (!response.ok) throw new Error((await response.text()) || 'Server xatosi');
    return response.json();
  };
  function toast(message){const el=document.querySelector('#toast');el.textContent=message;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2200);}
  function scoreClass(score){return score >= 75 ? '' : score >= 55 ? 'mid' : 'low';}
  function candidateRow(c){return `<button class="candidate" data-candidate="${c.id}"><span class="avatar">${esc(initials(c.full_name))}</span><span class="candidate-body"><h3>${esc(c.full_name)}</h3><p>${esc(c.vacancy_title)}</p><span class="status ${esc(c.status)}">${esc(statusNames[c.status]||c.status)}</span></span><span class="score ${scoreClass(c.score)}">${c.score == null?'—':esc(c.score)}</span></button>`;}
  function show(name){document.querySelectorAll('.view').forEach(x=>x.classList.toggle('active',x.id===name));document.querySelectorAll('.bottom-nav button').forEach(x=>x.classList.toggle('active',x.dataset.go===name));document.querySelector('.bottom-nav').hidden=name==='detail'||name==='error-view';window.scrollTo(0,0);if(name==='dashboard')loadDashboard();if(name==='candidates')loadCandidates();if(name==='vacancies')loadVacancies();if(name==='billing')loadBilling();}
  async function loadDashboard(){try{const d=await api('/dashboard');document.querySelector('#company').textContent=d.company;document.querySelector('#m-pending').textContent=d.stats.pending;document.querySelector('#m-accepted').textContent=d.stats.accepted;document.querySelector('#m-vacancies').textContent=d.active_vacancies;document.querySelector('#m-total').textContent=d.stats.total;const urgent=document.querySelector('#urgent');urgent.hidden=!d.stats.pending;document.querySelector('#urgent-count').textContent=`${d.stats.pending} ta yangi nomzod`;document.querySelector('#recent-list').innerHTML=d.recent.length?d.recent.map(candidateRow).join(''):'<div class="empty">Hozircha ariza yo‘q.</div>';document.querySelector('#plan-name').textContent=d.billing.plan;const limit=d.billing.applications_limit??'∞';document.querySelector('#plan-usage').textContent=`${d.billing.applications_used} / ${limit} ariza ishlatildi`;}catch(e){fail(e);}}
  async function loadCandidates(){const list=document.querySelector('#candidate-list');list.innerHTML='<div class="empty">Yuklanmoqda…</div>';try{const d=await api(`/candidates?status=${currentStatus}`);list.innerHTML=d.items.length?d.items.map(candidateRow).join(''):'<div class="empty">Bu bo‘limda nomzod yo‘q.</div>';}catch(e){fail(e);}}
  async function loadVacancies(){const list=document.querySelector('#vacancy-list');list.innerHTML='<div class="empty">Yuklanmoqda…</div>';try{const d=await api('/vacancies');list.innerHTML=d.items.length?d.items.map(v=>`<article class="vacancy"><div class="vacancy-head"><div><h3>${esc(v.title)}</h3><p>${v.active?'Nomzodlar uchun ochiq':'Yopilgan'}</p></div><button class="toggle ${v.active?'on':''}" data-toggle-vacancy="${esc(v.key)}" aria-label="Holatni o‘zgartirish"></button></div><div class="vacancy-meta"><span>${v.total} ariza</span><span>${v.pending} yangi</span><span>${v.questions} savol</span></div></article>`).join(''):'<div class="empty">Vakansiya yo‘q. Yangi vakansiyani admin botda yarating.</div>';}catch(e){fail(e);}}
  async function loadBilling(){try{const d=await api('/billing');document.querySelector('#current-plan').innerHTML=`<small>JORIY TARIF</small><h2>${esc(d.current.name)}</h2><p>${d.current.expires_at?'Amal qiladi: '+esc(d.current.expires_at.slice(0,10)):'Sinov rejimi'}</p>`;document.querySelector('#plans').innerHTML=d.plans.map(p=>`<article class="price-card ${p.code==='growth'?'popular':''}">${p.code==='growth'?'<span class="popular-tag">OMMABOP</span>':''}<div class="price-head"><div><h3>${esc(p.name)}</h3><p>${p.applications} ariza · ${p.vacancies} vakansiya</p></div></div><div class="price">${fmt(p.price)} so‘m</div><button data-open-bot>Tarifni tanlash</button></article>`).join('');}catch(e){fail(e);}}
  async function openCandidate(id){try{const c=await api(`/candidates/${id}`);const answers=Object.entries(c.answers||{}).map(([key,value])=>{const ai=c.ai_scores?.[key];return `<div class="answer"><b>JAVOB</b><p>${esc(value)}</p>${ai?.izoh?`<div class="ai-note">${esc(ai.izoh)}${ai.score!=null?` · ${esc(ai.score)}/100`:''}</div>`:''}</div>`}).join('');const actions=['pending','saved'].includes(c.status)?`<div class="decision-actions"><button data-decision="accept" data-id="${c.id}">Suhbatga chaqirish</button><button class="save" data-decision="save" data-id="${c.id}">Keyin ko‘rish</button><button class="reject" data-decision="reject" data-id="${c.id}">Rad etish</button></div>`:'';document.querySelector('#candidate-detail').innerHTML=`<article class="detail-card"><span class="status ${esc(c.status)}">${esc(statusNames[c.status]||c.status)}</span><h1>${esc(c.full_name)}</h1><div class="detail-meta">${esc(c.vacancy_title)} · ${esc(c.phone_number||'Raqam yo‘q')}</div><div class="detail-score"><span>AI moslik bahosi</span><strong>${c.score==null?'—':esc(c.score)+'/100'}</strong></div>${answers||'<div class="empty">Javoblar topilmadi.</div>'}${actions}</article>`;show('detail');}catch(e){toast(e.message);}}
  async function decide(id,action){const labels={accept:'Suhbatga chaqirilsinmi?',save:'Keyin ko‘rishga saqlansinmi?',reject:'Nomzod rad etilsinmi?'};if(!confirm(labels[action]))return;try{await api(`/candidates/${id}/decision`,{method:'POST',body:JSON.stringify({action})});tg?.HapticFeedback?.notificationOccurred('success');toast('Qaror saqlandi');show('candidates');}catch(e){toast(e.message);}}
  async function toggleVacancy(key){try{await api(`/vacancies/${encodeURIComponent(key)}/toggle`,{method:'POST',body:'{}'});tg?.HapticFeedback?.impactOccurred('light');loadVacancies();}catch(e){toast(e.message);}}
  function fail(error){document.querySelector('#error-message').textContent=error.message||'Mini Appni admin bot ichidan qayta oching.';show('error-view');}
  document.addEventListener('click',e=>{const go=e.target.closest('[data-go]');if(go)show(go.dataset.go);const candidate=e.target.closest('[data-candidate]');if(candidate)openCandidate(candidate.dataset.candidate);const filter=e.target.closest('[data-status]');if(filter){currentStatus=filter.dataset.status;document.querySelectorAll('[data-status]').forEach(x=>x.classList.toggle('active',x===filter));loadCandidates();}const decision=e.target.closest('[data-decision]');if(decision)decide(decision.dataset.id,decision.dataset.decision);const toggle=e.target.closest('[data-toggle-vacancy]');if(toggle)toggleVacancy(toggle.dataset.toggleVacancy);if(e.target.closest('[data-open-bot]')){tg?.close();toast('Tarifni admin bot orqali tanlang');}});
  document.querySelector('#refresh').addEventListener('click',()=>show(document.querySelector('.view.active')?.id||'dashboard'));
  document.querySelector('#retry').addEventListener('click',()=>show('dashboard'));
  tg?.ready();tg?.expand();tg?.setHeaderColor?.('#ffffff');tg?.setBackgroundColor?.('#f5f7fb');
  if(!initData){fail(new Error('Mini Appni kompaniyangizning Admin botidagi “Boshqaruv paneli” tugmasidan oching.'));}else{loadDashboard();}
})();
